/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsWeightRouteImport } from './routes/tools.weight'
import { Route as ToolsPriceRouteImport } from './routes/tools.price'
import { Route as ToolsHealthRouteImport } from './routes/tools.health'
import { Route as ToolsBreedRouteImport } from './routes/tools.breed'
import { Route as ToolsBcsRouteImport } from './routes/tools.bcs'
import { Route as AnimalIdRouteImport } from './routes/animal.$id'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWeightRoute = ToolsWeightRouteImport.update({
  id: '/tools/weight',
  path: '/tools/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPriceRoute = ToolsPriceRouteImport.update({
  id: '/tools/price',
  path: '/tools/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHealthRoute = ToolsHealthRouteImport.update({
  id: '/tools/health',
  path: '/tools/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBreedRoute = ToolsBreedRouteImport.update({
  id: '/tools/breed',
  path: '/tools/breed',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBcsRoute = ToolsBcsRouteImport.update({
  id: '/tools/bcs',
  path: '/tools/bcs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalIdRoute = AnimalIdRouteImport.update({
  id: '/animal/$id',
  path: '/animal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/animal/$id': typeof AnimalIdRoute
  '/tools/bcs': typeof ToolsBcsRoute
  '/tools/breed': typeof ToolsBreedRoute
  '/tools/health': typeof ToolsHealthRoute
  '/tools/price': typeof ToolsPriceRoute
  '/tools/weight': typeof ToolsWeightRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/animal/$id': typeof AnimalIdRoute
  '/tools/bcs': typeof ToolsBcsRoute
  '/tools/breed': typeof ToolsBreedRoute
  '/tools/health': typeof ToolsHealthRoute
  '/tools/price': typeof ToolsPriceRoute
  '/tools/weight': typeof ToolsWeightRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/animal/$id': typeof AnimalIdRoute
  '/tools/bcs': typeof ToolsBcsRoute
  '/tools/breed': typeof ToolsBreedRoute
  '/tools/health': typeof ToolsHealthRoute
  '/tools/price': typeof ToolsPriceRoute
  '/tools/weight': typeof ToolsWeightRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/scan'
    | '/animal/$id'
    | '/tools/bcs'
    | '/tools/breed'
    | '/tools/health'
    | '/tools/price'
    | '/tools/weight'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/scan'
    | '/animal/$id'
    | '/tools/bcs'
    | '/tools/breed'
    | '/tools/health'
    | '/tools/price'
    | '/tools/weight'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/scan'
    | '/animal/$id'
    | '/tools/bcs'
    | '/tools/breed'
    | '/tools/health'
    | '/tools/price'
    | '/tools/weight'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  AnimalIdRoute: typeof AnimalIdRoute
  ToolsBcsRoute: typeof ToolsBcsRoute
  ToolsBreedRoute: typeof ToolsBreedRoute
  ToolsHealthRoute: typeof ToolsHealthRoute
  ToolsPriceRoute: typeof ToolsPriceRoute
  ToolsWeightRoute: typeof ToolsWeightRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/weight': {
      id: '/tools/weight'
      path: '/tools/weight'
      fullPath: '/tools/weight'
      preLoaderRoute: typeof ToolsWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/price': {
      id: '/tools/price'
      path: '/tools/price'
      fullPath: '/tools/price'
      preLoaderRoute: typeof ToolsPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/health': {
      id: '/tools/health'
      path: '/tools/health'
      fullPath: '/tools/health'
      preLoaderRoute: typeof ToolsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/breed': {
      id: '/tools/breed'
      path: '/tools/breed'
      fullPath: '/tools/breed'
      preLoaderRoute: typeof ToolsBreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bcs': {
      id: '/tools/bcs'
      path: '/tools/bcs'
      fullPath: '/tools/bcs'
      preLoaderRoute: typeof ToolsBcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animal/$id': {
      id: '/animal/$id'
      path: '/animal/$id'
      fullPath: '/animal/$id'
      preLoaderRoute: typeof AnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  AnimalIdRoute: AnimalIdRoute,
  ToolsBcsRoute: ToolsBcsRoute,
  ToolsBreedRoute: ToolsBreedRoute,
  ToolsHealthRoute: ToolsHealthRoute,
  ToolsPriceRoute: ToolsPriceRoute,
  ToolsWeightRoute: ToolsWeightRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
